
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      target: production
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    networks:
      - net

  php:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
      target: production
    container_name: ${COMPOSE_PROJECT_NAME}_php
    user: www-data
    networks:
      - net

volumes:
  mysql_data:
    name: ${COMPOSE_PROJECT_NAME}_mysql_data

networks:
  net:
    name: ${COMPOSE_PROJECT_NAME}_net
