
services:
  nginx:
    build:
      target: development
    volumes:
      - ../app:/app
      - ./nginx/conf/default.development.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"

  php:
    build:
        target: development
    volumes:
      - ../app:/app
      - ./php-fpm/assets/xdebug.ini:/usr/local/etc/php/conf.d/zz-xdebug.ini

  mysql:
    image: mysql:8.0.31
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    ports:
      - "127.0.0.1:3306:3306"
      - "127.0.0.1:33060:33060"
    environment:
      MYSQL_USER          : ${SQL_USERNAME:?It seems you forgot to edit your .env file (SQL_* section)}
      MYSQL_DATABASE      : ${SQL_DATABASE:?It seems you forgot to edit your .env file (SQL_* section)}
      MYSQL_PASSWORD      : ${SQL_PASSWORD:?It seems you forgot to edit your .env file (SQL_* section)}
      MYSQL_ROOT_PASSWORD : ${SQL_ROOTPASS:?It seems you forgot to edit your .env file (SQL_* section)}
    networks:
      - net
    volumes:
#      - ./mysql/database.sql:/docker-entrypoint-initdb.d/database.sql
      - mysql_data:/var/lib/mysql
    command: >
      --default-authentication-plugin=mysql_native_password
