<?php

namespace Tests\Unit;

use App\Router;
use PHPUnit\Framework\TestCase;

class RouterTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->router = new Router();
    }

    public function test_it_registers_a_route() : void
    {
        //give a router obj
//        $router = new Router();

        //call register
        $this->router->register('get', '/users', ['Users', 'index']);

        $expected = [
            'get' => [
                '/users' => ['Users', 'index']
            ]
        ];

        //assert
        $this->assertEquals($expected, $this->router->routes());
    }

    /** @test */
    public function it_registers_get_route()
    {
//        $router = new Router();

        $this->router->get('/users', ['Users', 'index']);

        $expected = [
            'get' => [
                '/users' => ['Users', 'index']
            ]
        ];

        $this->assertEquals($expected, $this->router->routes());
    }

    /** @test */
    public function it_registers_post_route()
    {
//        $router = new Router();

        $this->router->post('/users', ['Users', 'store']);

        $expected = [
            'post' => [
                '/users' => ['Users', 'store']
            ]
        ];

        $this->assertEquals($expected, $this->router->routes());
    }

    public function test_no_routes_when_router_created()
    {
//        $router = new Router();

        $this->assertEmpty($this->router->routes());
    }
}